/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as NegocioSlugRouteImport } from './routes/negocio.$slug'
import { Route as TDeviceCodeRouteImport } from './routes/t.$deviceCode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const NegocioSlugRoute = NegocioSlugRouteImport.update({
  id: '/negocio/$slug',
  path: '/negocio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TDeviceCodeRoute = TDeviceCodeRouteImport.update({
  id: '/t/$deviceCode',
  path: '/t/$deviceCode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/negocio/$slug': typeof NegocioSlugRoute
  '/t/$deviceCode': typeof TDeviceCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/negocio/$slug': typeof NegocioSlugRoute
  '/t/$deviceCode': typeof TDeviceCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/negocio/$slug': typeof NegocioSlugRoute
  '/t/$deviceCode': typeof TDeviceCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explorar'
    | '/login'
    | '/registro'
    | '/negocio/$slug'
    | '/t/$deviceCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explorar'
    | '/login'
    | '/registro'
    | '/negocio/$slug'
    | '/t/$deviceCode'
  id:
    | '__root__'
    | '/'
    | '/explorar'
    | '/login'
    | '/registro'
    | '/negocio/$slug'
    | '/t/$deviceCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExplorarRoute: typeof ExplorarRoute
  LoginRoute: typeof LoginRoute
  RegistroRoute: typeof RegistroRoute
  NegocioSlugRoute: typeof NegocioSlugRoute
  TDeviceCodeRoute: typeof TDeviceCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocio/$slug': {
      id: '/negocio/$slug'
      path: '/negocio/$slug'
      fullPath: '/negocio/$slug'
      preLoaderRoute: typeof NegocioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$deviceCode': {
      id: '/t/$deviceCode'
      path: '/t/$deviceCode'
      fullPath: '/t/$deviceCode'
      preLoaderRoute: typeof TDeviceCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExplorarRoute: ExplorarRoute,
  LoginRoute: LoginRoute,
  RegistroRoute: RegistroRoute,
  NegocioSlugRoute: NegocioSlugRoute,
  TDeviceCodeRoute: TDeviceCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
