/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as BusinessIndexRouteImport } from './routes/business.index'
import { Route as BusinessConfiguracionRouteImport } from './routes/business.configuracion'
import { Route as BusinessDispositivosRouteImport } from './routes/business.dispositivos'
import { Route as BusinessSuscripcionRouteImport } from './routes/business.suscripcion'
import { Route as NegocioSlugRouteImport } from './routes/negocio.$slug'
import { Route as TDeviceCodeRouteImport } from './routes/t.$deviceCode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessConfiguracionRoute = BusinessConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessDispositivosRoute = BusinessDispositivosRouteImport.update({
  id: '/dispositivos',
  path: '/dispositivos',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessSuscripcionRoute = BusinessSuscripcionRouteImport.update({
  id: '/suscripcion',
  path: '/suscripcion',
  getParentRoute: () => BusinessRoute,
} as any)
const NegocioSlugRoute = NegocioSlugRouteImport.update({
  id: '/negocio/$slug',
  path: '/negocio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TDeviceCodeRoute = TDeviceCodeRouteImport.update({
  id: '/t/$deviceCode',
  path: '/t/$deviceCode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/business': typeof BusinessRouteWithChildren
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/registro': typeof RegistroRoute
  '/business/configuracion': typeof BusinessConfiguracionRoute
  '/business/dispositivos': typeof BusinessDispositivosRoute
  '/business/suscripcion': typeof BusinessSuscripcionRoute
  '/negocio/$slug': typeof NegocioSlugRoute
  '/t/$deviceCode': typeof TDeviceCodeRoute
  '/business/': typeof BusinessIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/registro': typeof RegistroRoute
  '/business/configuracion': typeof BusinessConfiguracionRoute
  '/business/dispositivos': typeof BusinessDispositivosRoute
  '/business/suscripcion': typeof BusinessSuscripcionRoute
  '/negocio/$slug': typeof NegocioSlugRoute
  '/t/$deviceCode': typeof TDeviceCodeRoute
  '/business': typeof BusinessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/business': typeof BusinessRouteWithChildren
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/registro': typeof RegistroRoute
  '/business/configuracion': typeof BusinessConfiguracionRoute
  '/business/dispositivos': typeof BusinessDispositivosRoute
  '/business/suscripcion': typeof BusinessSuscripcionRoute
  '/negocio/$slug': typeof NegocioSlugRoute
  '/t/$deviceCode': typeof TDeviceCodeRoute
  '/business/': typeof BusinessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/business'
    | '/explorar'
    | '/login'
    | '/perfil'
    | '/registro'
    | '/business/configuracion'
    | '/business/dispositivos'
    | '/business/suscripcion'
    | '/negocio/$slug'
    | '/t/$deviceCode'
    | '/business/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/explorar'
    | '/login'
    | '/perfil'
    | '/registro'
    | '/business/configuracion'
    | '/business/dispositivos'
    | '/business/suscripcion'
    | '/negocio/$slug'
    | '/t/$deviceCode'
    | '/business'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/business'
    | '/explorar'
    | '/login'
    | '/perfil'
    | '/registro'
    | '/business/configuracion'
    | '/business/dispositivos'
    | '/business/suscripcion'
    | '/negocio/$slug'
    | '/t/$deviceCode'
    | '/business/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BusinessRoute: typeof BusinessRouteWithChildren
  ExplorarRoute: typeof ExplorarRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  RegistroRoute: typeof RegistroRoute
  NegocioSlugRoute: typeof NegocioSlugRoute
  TDeviceCodeRoute: typeof TDeviceCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/': {
      id: '/business/'
      path: '/'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/configuracion': {
      id: '/business/configuracion'
      path: '/configuracion'
      fullPath: '/business/configuracion'
      preLoaderRoute: typeof BusinessConfiguracionRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/dispositivos': {
      id: '/business/dispositivos'
      path: '/dispositivos'
      fullPath: '/business/dispositivos'
      preLoaderRoute: typeof BusinessDispositivosRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/suscripcion': {
      id: '/business/suscripcion'
      path: '/suscripcion'
      fullPath: '/business/suscripcion'
      preLoaderRoute: typeof BusinessSuscripcionRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/negocio/$slug': {
      id: '/negocio/$slug'
      path: '/negocio/$slug'
      fullPath: '/negocio/$slug'
      preLoaderRoute: typeof NegocioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$deviceCode': {
      id: '/t/$deviceCode'
      path: '/t/$deviceCode'
      fullPath: '/t/$deviceCode'
      preLoaderRoute: typeof TDeviceCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BusinessRouteChildren {
  BusinessConfiguracionRoute: typeof BusinessConfiguracionRoute
  BusinessDispositivosRoute: typeof BusinessDispositivosRoute
  BusinessSuscripcionRoute: typeof BusinessSuscripcionRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
}

const BusinessRouteChildren: BusinessRouteChildren = {
  BusinessConfiguracionRoute: BusinessConfiguracionRoute,
  BusinessDispositivosRoute: BusinessDispositivosRoute,
  BusinessSuscripcionRoute: BusinessSuscripcionRoute,
  BusinessIndexRoute: BusinessIndexRoute,
}

const BusinessRouteWithChildren = BusinessRoute._addFileChildren(
  BusinessRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BusinessRoute: BusinessRouteWithChildren,
  ExplorarRoute: ExplorarRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  RegistroRoute: RegistroRoute,
  NegocioSlugRoute: NegocioSlugRoute,
  TDeviceCodeRoute: TDeviceCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
